config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :offers, except: [:edit] do
    resources :reservations, only: [:new, :create]
    collection do
      get :dashboard
    end
  end
  resources :reservations, only: [:show, :destroy] do
    # new route to change the status of the reservation
    get :accept_status
    get :reject_status
  end
  # don't forget to except "edit and destroy" to nest with users routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :photo
  validates :title, presence: true
  validates :availability, presence: true
  validates :location, presence: true
  validates :price_per_hour, presence: true
  validates :offer_description, presence: true, length: { minimum: 30 }
  validates :santa_description, presence: true, length: { minimum: 30 }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  validates :event_adress, presence: true
  validates :reservation_start, presence: true
  validates :reservation_end, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :offers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

         # a tester validates first and last name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # pour demander le login
  before_action :authenticate_user!

  # pour first name last name permit
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @offers = Offer.all
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render 'new'
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def dashboard
    @offers = Offer.where(user_id: current_user)
    @reservations = Reservation.where(user_id: current_user)
  end

  def destroy
    @offer = Offer.find(params[:id])
    puts 'success destroy -_-'
    @offer.destroy
    redirect_to dashboard_offers_path
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :availability, :location, :price_per_hour, :offer_description,
                                  :santa_description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # a faire method private before_action :find_user, only: [:create]
  # a faire method private before_action :find_offer, only: [:create]

  def new
    @reservation = Reservation.new
    @user = current_user
    @offer = Offer.find(params[:offer_id])
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.offer = @offer
    if @reservation.save!
      redirect_to dashboard_offers_path, notice: "creation success"
    else
      render 'reservations/new'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @offer = Offer.find(@reservation.offer_id)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to dashboard_offers_path, notice: 'destroy successfully'
  end

  def accept_status
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.status = "accepted"
    @reservation.save!
    redirect_to dashboard_offers_path, notice: "reservation accepted"
  end

  def reject_status
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.status = "rejected"
    @reservation.save!
    redirect_to dashboard_offers_path, notice: "reservation rejected"
  end

  private

  def reservation_params
    params.require(:reservation).permit(:event_adress, :reservation_start, :reservation_end)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloseSanta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%# decommenter la ligne 12 pour le fonctionnement de mon log_out %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/offers/dashboard.html.erb
<%# function for display 🎅🏻 or 🧑🏻 %>
<% if user_signed_in? %>
<% if current_user.offers.present?%>
<% is_santa = "🎅🏻" %>
<% else %>
<% is_santa = "🧑🏻" %>
<% end %>
<% end %>

<div class=top-message-div>
<h2 id="top-message"><%=is_santa%> <%= current_user.firstname %>'s Dashboard 🎁<h2>
<div class="bouton-index">
<%= link_to "Back to offers", offers_path, class:"pill m-2" %>
<%= link_to "Create an offer", new_offer_path, class:"pill pill-color m-2" %>
</div>
</div>


<div class="flexcenter">




      <% @offers.each do |offer| %>


         <div class="offers-card">
              <div style="background-image: url(<%= cl_image_path offer.photo.key, height: 250, width: 500, crop: :fill %>);" class="image-left-content" >
              </div>

              <div class="user-offers-card-right-content">

                <div class="offer-description">
                  <h4><b>My offer 🎅🏻</b><br>
                  <%=link_to "#{offer.title}", offer_path(offer) %></h4> <hr>

                  <p> <b>Available:</b> in <%= offer.location %> the <%= offer.availability %></p>
                      <p><b>Price : <%= offer.price_per_hour %> € </b>
                      <% unless offer.reservations.present? %>
                         - no reservation yet 😢 </p>
                        <%else%>
                        - Someone is intereted 😎 </p>
                      <% end %>


                      </p>

                </div>

              <% if offer.user.id == current_user.id && offer.reservations.present?%>
                <% offer.reservations.each do |reservation| %>
                <div class="if-reserve">
                <h4> 🧑🏻 <b><%= reservation.user.firstname %> wants a santa</b></h4>
                  <p><b>Adress:</b> <%= link_to "#{reservation.event_adress}", reservation_path(reservation)  %>
                  <br> <b>Start at:</b> <%= reservation.reservation_start.strftime(" %I:%M %p") %> <br> <b>End at:</b><%= reservation.reservation_end.strftime(" %I:%M %p") %></p>

                    <%# - à ajouter si necessaire
                  <p>Status: <%= reservation.status %></p>
                    <% if reservation.status == "pending" %>

                      <div id="button-dashboard-div">
                      <%= link_to "accept", reservation_accept_status_path(reservation), class:"bouton-white"  %>
                      <%= link_to "Reject", reservation_reject_status_path(reservation), class:"bouton-red"  %>
                      </div>
                    <% end %>

                    <% if reservation.status == "accepted" %>
                    <a class="bouton-white" href="mailto:<%=reservation.user.email%>"> contact <%= reservation.user.firstname%> </a>
                    <% end %>
                    <% if reservation.status == "rejected" %>
                      <p> this reservation is <%= reservation.status %> 😭 </p>
                    <% end %>
                </div>
      <% end %>








      <% end %>
        </div>
    </div>
      <% end %>





    <div class='offer-dashboard'>



      <% @reservations.each do |reservation| %>
        <div class="offers-card">

                    <div style="background-image: url(<%= cl_image_path reservation.offer.photo.key, height: 250, width: 500, crop: :fill %>);" class="image-left-content" >
                    </div>

                    <div class="user-offers-card-right-content">


                            <div class="offer-description">
                                                  <h4><b>My reservation 🧑🏻</b><br>
                                                  <%=link_to "#{reservation.offer.title}", reservation_path(reservation) %></h4><hr>

                                                  <p><b>Address: </b><%=link_to "#{reservation.event_adress}", reservation_path(reservation) %></p>
                                                  <p> <b>The <%= Offer.find(reservation.offer_id).availability %> :</b> from <%= reservation.reservation_start.strftime("%H:%M") %> to <%= reservation.reservation_end.strftime("%H:%M") %></p>
                                                          <% if reservation.status == "pending" %>
                                                  <p>Your santa has not accepted yet 😞</p><br>
                                                  <%= link_to "Cancel",
                                                      reservation,
                                                      method: :delete,
                                                      data: { confirm: "Are you sure?" },class:"bouton-red"%>
                                                <% end %>
                                                <% if reservation.status == "rejected" %>
                                                <p>Santa rejected your reservation 😭</p><br>
                                                  <%= link_to "Delete",
                                                      reservation,
                                                      method: :delete,
                                                      data: { confirm: "Are you sure?" },class:"bouton-red"%>

                                          <% end %>
                                                <% if reservation.status == "accepted" %>
                                                <p>Santa accept your reservation 🥳</p><br>
                                                <a class="bouton-green" href="mailto:<%=reservation.offer.user.email%>"> Contact <%=reservation.offer.user.firstname%> </a>

                                          <% end %>
                            </div>
                     </div>
        </div>
                                        <% end %>
    </div>
</div>
</div>

app/views/offers/index.html.erb
<%#😶‍🌫️  <% @offers.each do |offer| %>
<%#😶‍🌫️  <p><%= link_to offer.title, offer_path(offer) %>   <%#😶‍🌫️   </p>
<%#😶‍🌫️  <% end %>
<%#😶‍🌫️  <%= link_to "Create a new offer", new_offer_path %>

<%# face base number outside loop%>
<% number = 1 %>

<%# top-message %>
<div class=top-message-div>
<h1 id="top-message">🎄 Choose your Santa<h1>
<div class="bouton-index">
<%= link_to "add yours!", new_offer_path, class:"pill pill-color"%>
</div>
</div>



<%# Content %>
<div class="cards-content" id="column-small">

  <%# change with local file %>
  <% @offers.each do |offer| %>
    <% random = number%>
    <% face = "https://www.virgilearlaud.fr/wagon/faces/#{random}.jpeg"%>
    <% number += 1%>

    <div class="card">
    <%= link_to offer_path(offer) do %>

        <div class="card-img" style="background-image: url(<%= cl_image_path offer.photo.key, height: 250, width: 600, crop: :fill, gravity: :face %>);">
        </div>

      <div class="btmcontent">
        <div>
          <h6><%= offer.title %></h6>
          <h4 class="price">  <%= offer.price_per_hour %> €</h4>
        </div>
        <div class="btmcontent-right">
          <h6><%= offer.availability %><h6> <h6><%= offer.location%><h6>
        </div>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/offers/new.html.erb
<div class=top-message-div>
<h2 id="top-message"> 🎅🏻 Your Santa<br>Prestation 💰 </h2>
</div>

<div class="d-flex justify-content-center">
<div class="fcontent">
<%= simple_form_for(@offer)  do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :price_per_hour %>
  <%= f.input :offer_description %>
  <%= f.input :santa_description %>
  <%= f.input :availability %>
  <%= f.input :photo, as: :file%>
  <div class="d-flex justify-content-center">
  <%= link_to "back to offers", offers_path, :id => "black-btn-form" %>
  <%= f.submit "publish", :id => "green-btn-form" %>
  </div>
<% end %>
</div>
</div>

app/views/offers/show.html.erb
<div class="show-content">

<% if @offer.user == current_user %>

  <div class="show-description-content">
    <%= simple_form_for(@offer) do |f| %>
      <%= f.input :title %>
      <%= f.input :location %>
      <%= f.input :price_per_hour %>
      <%= f.input :offer_description %>
      <%= f.input :santa_description %>
      <%= f.input :availability %>
      <%= f.input :photo, as: :file%>
      <div class="d-flex justify-content-center" >
      <%= f.submit "update", class: "bouton-green" %>
      </div>
    <% end %>
  </div><%# end of description%>

<% else %>

  <div class="show-description-content">
  <h2>Say Hello to <%=@offer.user.firstname%> ! 👋 </h2>
  <h2 id="subtitle"><%= @offer.title %></h2>
    <hr>
  <h3>Here is more about <%=@offer.user.firstname%>:</h3>
  <p><%= @offer.santa_description %></p>
  <br>
  <h3>Why <%=@offer.user.firstname%> ?</h3>
  <br>
  <p><%= @offer.offer_description %></p>
  <br>
  <h3>Our santa disponibility: </h3>
  <p><b>The <%= @offer.availability.to_time.strftime('%e %B %Y') %></b> in <%= @offer.location %></p>
  <br>
  <h3>Price per hour: </h3>
  <h4><%= @offer.price_per_hour %> €</h4 >
  </div><%# end of description%>


<% end %>


  <div class="show-picture-content" style="background-image: url(<%= cl_image_path @offer.photo.key, height: 500, width: 200%>);">
  <%= link_to "😒 Go Back", offers_path, :class => "bouton-black" %>
  <%# pour que le createur de l'offre ne puisse pas la reserver %>
  <% unless @offer.user_id == current_user.id %>
  <%= link_to '❤️ Reserve !', new_offer_reservation_path(@offer), class: "bouton-green" %>
  <% end %>



<% if @offer.user == current_user %>
<%= button_to "🗑 Delete",
            @offer,
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: "bouton-red"%>
<% end %>

</div><%# end of picture%>

</div><%# end of content%>

app/views/pages/home.html.erb
<div class=container>
  <header class="first-card">
    <div class="filter-div">
      <h1>Welcome.</h1>
      <h2>to Close Santa</h2>
      <hr>
      <p>Here you can find your Santa next to your location <br> and rent him for a special christmas time.</p>
      <br>

      <%= link_to "Find a santa !", offers_path, class:"pill pill-color pill-text" %>
     </div>
    </header>

   <%# <div class="second-card">
    <article class="display-text" >
      <section>
        <h3>How to rent a Santa ?</h3>
        <p>Welcome to Close Santa, the best website to rent your santa for christmas time.
          Here you can see all the Santa's offer by location and time period.
          You can choose a Santa on his description, his prestation show.</p>
      </section>
      <section>
        <h3>Become a Santa ?</h3>
        <p>You can be a Santa to bring some joy to the childs and help parents.</p>
      </section>
   <article id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d740916.9687744919!2d5.757158441591807!3d43.49801901265715!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12cdd10cf23b0b5d%3A0xb08b358b054a5bf7!2sLe%20Wagon%20Nice!5e0!3m2!1sfr!2sfr!4v1637967652356!5m2!1sfr!2sfr"
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
     </article> %>
</div>

app/views/reservations/new.html.erb
<div class=top-message-div>
<h2 id="top-message"> 🎅🏻 Your Santa<br>Reservation 🎄<h2>
</div>

<%= simple_form_for([@offer, @reservation]) do |f| %>

<div class="d-flex justify-content-center">
<div class="fcontent">
    <%= f.input :event_adress %>
    <%= f.input :reservation_start, as: :time, html5: true %>
    <%= f.input :reservation_end, as: :time, html5: true %>
    <div class="d-flex justify-content-center">
    <%= link_to 'back to offer', offer_path(@offer), :id => "black-btn-form"%>
    <%= f.submit "reserve", :id => "green-btn-form" %>
  </div>

<% end %>
</div>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <div class="show-description-content text-center">
    <div class="text-center">
      <h3>Reservation at <%= @reservation.event_adress %></h3>
      <br/>
      <p>Starting at: <%= @offer.availability.to_time.strftime('%e %B %Y') %> <%= @reservation.reservation_start.strftime("at %I:%M %p") %></p>
      <p>Ending at: <%= @offer.availability.to_time.strftime('%e %B %Y') %> <%= @reservation.reservation_end.strftime("at %I:%M %p") %></p>
      <p>Status: <%= @reservation.status %></p>
    </div>

    <%# if the current user is the user who created the reservation %>
    <% if @reservation.user.id == current_user.id %>
      <div class="d-inline-flex bouton-group">
      <% if @reservation.status == "pending" %>
        <%= link_to "Cancel",
            @reservation,
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: "bouton-black"%>
      <% end %>
      <% if @reservation.status == "rejected" %>
        <%= link_to "Delete",
            @reservation,
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: "bouton-black"%> %>
      <% end %>
      </div>
    <% end %>

    <%# if the current user is the user who created the offer linked to the reservation %>
    <% if @reservation.offer.user.id == current_user.id %>
      <% if @reservation.status == "pending" %>
        <div class="d-inline-flex bouton-group">
          <%= link_to "Accept", reservation_accept_status_path(@reservation), class: "bouton-green" %>
          <%= link_to "Reject", reservation_reject_status_path(@reservation), class: "bouton-red" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to 'Back to my dashboard', dashboard_offers_path, class: "bouton-white" %>
</div>